import {useEffect,useRef,useState,type CSSProperties,type PointerEvent as ReactPointerEvent} from "react";
type Props={section?:string};
const points=[{id:"top",label:"START",x:.86,y:.2},{id:"services",label:"SERVICES",x:.14,y:.38},{id:"discover",label:"DISCOVER",x:.82,y:.52},{id:"process",label:"PROCESS",x:.18,y:.67},{id:"tools",label:"TOOLS",x:.78,y:.8},{id:"contact",label:"BOOK",x:.2,y:.9}];
export default function RobotAssistant({section="START"}:Props){
 const [pos,setPos]=useState({x:.86,y:.2}),[look,setLook]=useState({x:0,y:0}),[drag,setDrag]=useState(false),[label,setLabel]=useState(section),[state,setState]=useState("idle");
 const p=useRef(pos),target=useRef(pos),offset=useRef({x:0,y:0});
 useEffect(()=>{let raf=0;const tick=()=>{const a=p.current,b=target.current,e=drag?.22:.065,n={x:a.x+(b.x-a.x)*e,y:a.y+(b.y-a.y)*e};p.current=n;setPos(n);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[drag]);
 useEffect(()=>{const move=(e:PointerEvent)=>{setLook({x:e.clientX/innerWidth-.5,y:e.clientY/innerHeight-.5});if(drag){target.current={x:Math.min(.94,Math.max(.06,(e.clientX-offset.current.x)/innerWidth)),y:Math.min(.92,Math.max(.08,(e.clientY-offset.current.y)/innerHeight))};setState("drag");setLabel("DROP ME")}};const up=()=>{if(drag){setDrag(false);setState("rest");setLabel("STUDIO GUIDE")}};addEventListener("pointermove",move,{passive:true});addEventListener("pointerup",up);return()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)}},[drag]);
 useEffect(()=>{const update=()=>{const marker=scrollY+innerHeight*.42;let c=points[0];for(const x of points){const el=document.getElementById(x.id);if(el&&el.offsetTop<=marker)c=x}if(!drag){target.current={x:c.x,y:c.y};setLabel(c.label);setState(c.id==="contact"?"celebrate":"moving")}};update();addEventListener("scroll",update,{passive:true});return()=>removeEventListener("scroll",update)},[drag]);
 const down=(e:ReactPointerEvent<HTMLButtonElement>)=>{e.preventDefault();const r=e.currentTarget.getBoundingClientRect();offset.current={x:e.clientX-(r.left+r.width/2),y:e.clientY-(r.top+r.height/2)};setDrag(true);setState("drag");setLabel("DROP ME")};
 return <button type="button" className={`guide-robot is-${state}`} aria-label="Drag the Studio guide" onPointerDown={down} onDoubleClick={()=>document.getElementById("builder-trigger")?.click()} style={{"--rx":`${pos.x*100}vw`,"--ry":`${pos.y*100}vh`,"--look-x":look.x,"--look-y":look.y} as CSSProperties}><span className="guide-robot__halo"/><span className="guide-robot__antenna"/><span className="guide-robot__head"><i/><i/></span><span className="guide-robot__neck"/><span className="guide-robot__body"><i/><b/></span><span className="guide-robot__arm guide-robot__arm--left"/><span className="guide-robot__arm guide-robot__arm--right"/><span className="guide-robot__hand guide-robot__hand--left"/><span className="guide-robot__hand guide-robot__hand--right"/><span className="guide-robot__leg guide-robot__leg--left"/><span className="guide-robot__leg guide-robot__leg--right"/><span className="guide-robot__foot guide-robot__foot--left"/><span className="guide-robot__foot guide-robot__foot--right"/><span className="guide-robot__label mono">{label}</span></button>;
}